### ISSUE TITLE
Scripts automatización virtualización

### ISSUE THREAD

**Issue by DavidGSola** [HarmaDev/HarmacenCloud#19]
El entorno de pruebas debe ser reproducible, por lo tanto es necesario la creación de una serie de **scripts** que permitanen crear fácilmente ese entorno en una instalación sin jaulas ni contenedores, y reproducir la aplicación que se va a probar.

**Comment by jmrosell** [comment]
No es necesario, puesto que, no necesitamos crear jaulas o contenedores. Nuestros script se ejecutan directamente en los servicios de Google.
