### ISSUE TITLE
Integrar calendario + formulario1

### ISSUE THREAD

**Issue by DavidGSola** [HarmaDev/HarmacenCloud#20]
Integrar la creación del evento de Google Calendar en el formulario1 de petición de recogida de materiales.

**Comment by Georgevik** [comment]
En el formulario no tiene lugar introducir un calendario

**Comment by Georgevik** [comment]
Se va a hacer un formulario donde tenga los siguientes campos:
- Fecha recogida
- Correo del interesado
- Lugar
- Descripcion

Al pulsar debe enviar un correo con los campos al correo electronico indicado y un evento en el Calendar del anfitrion

**Comment by Georgevik** [comment]
Añadido en el commit 02f19cd27b7d9af011580c2d3d14142636ea2059
