### ISSUE TITLE
Crear formulario de recogida realizada

### ISSUE THREAD

**Issue by DavidGSola** [HarmaDev/HarmacenCloud#23]
Es necesario crear un formulario que se debe rellenar cuando se completa una recogida. Este formulario debe añadir a la hoja de cálculo los equipos recogidos. Se debe poder elegir que tipo de equipo se ha recogido (impresora, sobremesa, portatil, etc) y que en función de ello el formulario sea distinto.

**Comment by jorgeles** [comment]
Voy a hacer una primera versión

**Comment by DavidGSola** [comment]
Se ha descartado esta funcionalidad
