### ISSUE TITLE
Preguntas para Psicobyte

### ISSUE THREAD

**Issue by antorof** [HarmaDev/HarmacenCloud#24]
Preguntas para entrevista con Psicobyte relativas al almacén de la OSL.

**Comment by antorof** [comment]
- Significado de cada hoja (tabla), para qué sirve cada una.
- Hojas necesarias y cuáles no.
- ¿Crear hoja/s para la entrada de material? ¿cuáles? ¿contenido? ¿separar por tipos (ordenadores, impresoras, periféricos de otros tipos...)?
- ¿Mover elementos entre hojas?

**Comment by jorgeles** [comment]
-Acciones tras la recogida de un componente o portátil.
-Acciones para poner en "listo" un ordenador.
-Como se realizan los informes.

**Comment by jorgeles** [comment]
- Que cambiaria de los pasos que se realizan en el proceso de recogida o de reciclaje de un componente.
- Preguntar por lo QR

**Comment by antorof** [comment]
- ¿Hojas separadas para cada tipo de material ya en el almacén o todas juntas?
-  ¿Distintas hojas para distintos estados (prestado, donado, en la oficina...) o la misma hoja con cada elemento con un estado distinto? Especificar.

**Comment by DavidGSola** [comment]
Añado una que ha surgido a raiz de ver el código original de su formulario de recogida:
- ¿Se debería enviar un correo a algún administrador de la OSL cada vez que alguien rellena el formulario de recogida?

**Comment by antorof** [comment]
Reunión cancelada.
